Preparing for the Python 3 switch + minor changes.
* Client build and repacking process made Python 3 compatible.
* Docker images used by CI are updated.
* More work on next-gen Angular UI.
* YARA fixes.
* Logging source IP in webauth.
* Version bump.

diff --git a/docker/Dockerfile.centos6 b/docker/Dockerfile.centos6
--- a/docker/Dockerfile.centos6
+++ b/docker/Dockerfile.centos6
@@ -22,7 +22,17 @@ RUN yum update -y && yum install -y zlib-devel bzip2-devel ncurses-devel \
   libffi-devel openssl-devel zip git gcc gcc-c++ redhat-rpm-config rpm-build \
   rpm-sign
 
-# Build a recent version of Python from source (Centos 6 has Python 2.6
+# Install a recent version of sqlite. CentOS-provided one is too old
+# for Python 3.
+RUN curl -sO https://sqlite.org/2017/sqlite-autoconf-3160200.tar.gz && \
+  tar xfz sqlite-autoconf-3160200.tar.gz && \
+  cd sqlite-autoconf-3160200 && \
+  ./configure && \
+  make install && \
+  cd .. && \
+  rm -rf sqlite-autoconf-3160200*
+
+# Build a recent version of Python 2 from source (Centos 6 has Python 2.6
 # installed in /usr/bin). The custom Python version is installed in
 # /usr/local/bin
 RUN wget https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tgz && \
@@ -33,10 +43,22 @@ RUN wget https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tgz && \
   make && \
   make altinstall
 
-# Install pip and virtualenv.
+# Install Python 2 pip and virtualenv.
 RUN wget https://bootstrap.pypa.io/get-pip.py && \
   python2.7 get-pip.py && \
   pip install --upgrade pip virtualenv
+
+# Build Python 3 from source.
+RUN wget https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tgz && \
+  tar xzvf Python-3.6.9.tgz && \
+  cd Python-3.6.9 && \
+  ./configure --enable-shared --enable-ipv6 --prefix=/usr/local \
+    LDFLAGS="-Wl,-rpath /usr/local/lib" && \
+  make && \
+  make altinstall
+
+# TSK currently fails with sqlite-devel, so we have to remove it from the Docker container.
+RUN yum remove -y sqlite-devel || true
 
 WORKDIR /
 
